### ISSUE TITLE
Nebra Rock pi Indoor - beacon/witness pattern: can witness fine until a beacon is sent

### ISSUE THREAD

**Issue by hawamahal1** [NebraLtd/helium-nebra-indoor2#3]
The issue I am having is similar to this issue posted in 2021, I  am located in Australia if that makes any difference. Since Australia had a few frequency changes in the last about 9 months. AU915 to AS923 and back to AU915.

#https://github.com/helium/miner/issues/1133

I just recently onboarded in new Nebra Rock pi indoor version. The original firmware was 2022.08.17.1 (4492c46) and asserted location.. Even after 24 hours of leaving it connected to the internet (ethernet), the dashborad still said " Awaiting Location Assertion" 

I updated the firmware to the latest version from hub.nebra.com and now on the dashboard all looks OK, but the hotspot stops witnessing as soon as it beacons. The sequence is as follows

1. hotspot witnesses other beacons
2. hotspot sends own beacons
3. hotspot own beacon returns 0
4. hotspot stops witnessing

If i restart the hotspot the same sequence repeats. If I leave it ON and connected, it tries to beacon every 6 hours, but gets no witnessing. Also I have checked heliumgeek and moken explorer, the hotspot does not witness anything selected or unselected or invalid.

**Comment by shawaj** [comment]
Hotspot looks fine to me and is still witnessing https://heliumtracker.io/hotspots/1026512

**Comment by shawaj** [comment]
Ticket 430636

**Comment by hawamahal1** [comment]
thanks for looking into it. It does not look fine to me at all. It only witnesses when I restart the hotspot and then stops witnessing after it beacons. https://explorer.moken.io/hotspots/112RWc6zYvRQLdZari4tAhusu6NVyiNU5QgEDHGZgNpRmD69HNTy/activity?activityRange=12H&selectedActivities=Witness,Beacon&selectedLayer=hotspots

If i flash an old firmware it keeps on working for say an hour and then as soon as it updates to new firmware, it stops soon after when it beacons.

i will leave it on without switching off for the next 12 hours and you will see only invalid beacons and no witnessing.

**Comment by shawaj** [comment]
Look at helium tracker link I sent. It looks fine.

Also, I see you have 5dbi antenna asserted.

Make sure antenna is connected properly.

**Comment by hawamahal1** [comment]
Thanks for your message. I have been looking at helium tracker and the moken explorer as well for the past 1 week.  Helium tracker does not tell the full story. Even with helium tracker you can see that once the hotspot beacons there is no more witnesses. Below is the screenshot of moken explorer taken now 6.16am AEST ( sydney time), you can clearly see that it was witnessing after a restart and once it beacons it stops witnessing totally ( selected or unselected).  I also checked the Antenna nothing wrong it is a  6 dbi antenna on the roof, so I entered 5 dbi to account for cable loss. Also we can rule out the antenna, as the antenna works fine as soon as we restart the unit and also with an older version of firmware.

![image](https://github.com/NebraLtd/helium-nebra-indoor2/assets/141073556/dfe75a3c-be59-40b4-981b-b568d86aad0b)

**Comment by shawaj** [comment]
The firmware hasn't changed between v1.0.2-2 and v1.0.2-52 ... gateway-rs from helium is still the same as is the packet forwarder and there is no other changes there other than to stuff that does not effect the radio side (info displayed in diagnostics)

Your miner is also on correct frequency of au915.

It's almost certainly a loose antenna, concentrator or cables to the antenna.

**Comment by shawaj** [comment]
Also rebooting it constantly likely is not helping things

**Comment by hawamahal1** [comment]
Thanks for your reply/ I checked the antenna connectors and plugged it back in. Hopefully it helps. Is there any way to stop automatic updates. I want to run an older version of the firmware in order to troubleshoot this issue.

**Comment by shawaj** [comment]
There is no way to turn off the updates I'm afraid.

In any case, as I said nothing has changed on the software that could cause what you are describing.

**Comment by hawamahal1** [comment]
Thanks for your help Aaron in troubleshooting my hotspot. I can confirm that the problem has nothing to do with the firmware. The hotspot has been running fine for the last about 24 hours with the latest firmware.

It looks like the problem was over heating of the most likely the concentrator module. I felt the hotspot was too hot by touching, so I removed the plastic cover off and put a small fan next to it and it has been running fine since then.

**Comment by shawaj** [comment]
Thanks for the update and good to know it's working ok now 👍
